lightgbm:
  objective: "multiclass"
  num_class: 4
  metric: "multi_logloss"
  learning_rate: 0.05
  num_leaves: 31
  random_state: 42
  num_boost_round: 100

dnn:
  layers: [128, 64]
  dropout: [0.3, 0.2]
  activation: "relu"
  output_activation: "softmax"
  optimizer: "adam"
  epochs: 10
  batch_size: 64